### ISSUE TITLE
Installation on Windows 7

### ISSUE THREAD

**Issue by ejmurray** [mcs07/ChemDataExtractor#3]
DAWG doesn't seem to install and there is a problem with lxml.

**Comment by mcs07** [comment]
These components use C++ behind the scenes for improved performance, so require a compiler. I managed to get them to install with `pip` on Windows 10 by installing the Visual C++ build tools from here: http://landinghub.visualstudio.com/visual-cpp-build-tools

But this isn't really an ideal situation. I think a better solution for Windows support is to use Anaconda, because it uses binary packages for each platform. I will need to put together a ChemDataExtractor conda recipe, but then `conda install ChemDataExtractor` should work without a compiler.

**Comment by ejmurray** [comment]
Slight problem in that it is looking for it in a win-64 directory when trying to install via Anaconda.

> Fetching package metadata .................Error: Could not find URL: https://gi
> thub.com/mcs07/ChemDataExtractor/win-64/

**Comment by ejmurray** [comment]
The .condarc file points to:

https://github.com/mcs07/ChemDataExtractor

**Comment by mcs07** [comment]
Yeah sorry, I haven't made the conda recipe yet. I'll post here when it's done.

**Comment by ejmurray** [comment]
Thanks again. I'm looking forward to testing it on some metabolism/metabolomics papers hence the constant barrage of questions (testing/getting it up an running).

**Comment by mcs07** [comment]
Windows packages are now available on the `chemdataextractor` conda channel. There should be no need to add anything to your `.condarc` file, just run `conda install -c chemdataextractor chemdataextractor`
